// This file is autogenerated. Changes will be overwritten.
#include "NPUKSKGWT2/moc_VitalController.cpp"
#include "NLOY5YBGEN/moc_VitalModel.cpp"
#include "OTUN7GXZT4/moc_MainWindow.cpp"
#include "OTUN7GXZT4/moc_WaveformWidget.cpp"
